-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: May 20, 2024 at 11:30 PM
-- Server version: 8.2.0
-- PHP Version: 8.2.13

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `streamingshows`
--

-- --------------------------------------------------------

--
-- Table structure for table `streaming_shows`
--

DROP TABLE IF EXISTS `streaming_shows`;
CREATE TABLE IF NOT EXISTS `streaming_shows` (
  `id` int NOT NULL AUTO_INCREMENT,
  `my_review` text,
  `my_ratepercent` int DEFAULT NULL,
  `my_recommend_yn` varchar(1) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `overview` varchar(5000) DEFAULT NULL,
  `year` varchar(4) DEFAULT NULL,
  `genres_name` varchar(255) DEFAULT NULL,
  `directors` varchar(255) DEFAULT NULL,
  `cast` varchar(255) DEFAULT NULL,
  `rating` varchar(255) DEFAULT NULL,
  `imageSet_horizontalPoster_w480` varchar(1000) DEFAULT NULL,
  `streamingOptions_ie_service_name` varchar(255) DEFAULT NULL,
  `streamingOptions_ie_service_imageSet_lightThemeImage` varchar(255) DEFAULT NULL,
  `streamingOptions_ie_type` varchar(255) DEFAULT NULL,
  `streamingOptions_ie_link` varchar(255) DEFAULT NULL,
  `streamingOptions_ie_quality` varchar(255) DEFAULT NULL,
  `streamingOptions_ie_price_formatted` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=21 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `streaming_shows`
--

INSERT INTO `streaming_shows` (`id`, `my_review`, `my_ratepercent`, `my_recommend_yn`, `title`, `overview`, `year`, `genres_name`, `directors`, `cast`, `rating`, `imageSet_horizontalPoster_w480`, `streamingOptions_ie_service_name`, `streamingOptions_ie_service_imageSet_lightThemeImage`, `streamingOptions_ie_type`, `streamingOptions_ie_link`, `streamingOptions_ie_quality`, `streamingOptions_ie_price_formatted`) VALUES
(1, 'This move kept me in suspense right up until the end. Recommended! ', 88, 'Y', '\"BLESSED\"', 'Supreme presents, \"BLESSED\" a full length video directed by William Strobeck featuring Tyshawn Jones, Ben Kadow, Sean Pablo, Aidan Mackey, Na-kel Smith, Sage Elsesser, Vincent Touzery, Kevin Bradley, Rowan Zorilla, Kevin Rodrigues, Mark Gonzales, Jason Dill. . .', '', 'Documentary', '', '', '', 'https://www.movieofthenight.com/media/image.svg?title=%22BLESSED%22&width=480&direction=horizontal', 'Apple TV', 'https://media.movieofthenight.com/services/apple/logo-light-theme.svg', 'rent', 'https://tv.apple.com/ie/movie/blessed---supreme/umc.cmc.3rhiiv16ny0avim81jotg82z3?playableId=tvs.sbd.9001%3A1440921537', 'hd', '4.99 EUR'),
(2, '', 0, '', '#AnneFrank. Parallel Stories', 'Actress Helen Mirren retraces Anne Frank\'s life through the pages of her diary, and through the lives of five woman who, as young girls, were also deported to concentration camps but escaped the Holocaust.', '', 'Documentary', '', '', '', 'https://cdn.movieofthenight.com/show/68162/poster/horizontal/en/480.jpg?Expires=1742251569&Signature=bCGVmy5i4JGh3FormhiaDSb4XWdQmrMGXc1LY3jhcaiqsEo2DpwiSXx7KoQxU6jI4aez3SMfOagUJ05Nb8Wtoj28W6TiYDR3WDPjItE4MwDRDffOdjviNE133Cl4I8XnS2U4aTMWAsVqLm9Y3t1mGvgQ~BgARMI4k~Ldbh-VKFtiPIPB04nEb6Z3DKzwGvsWjhBTz1eLnsC9PuspE5qseRZB1fWkHYa7JFAytjgP6cN9G9IXz8kbpSJGk0lhqFnV149aas9caZfsm7idE3nRX4CsiA6dvl~kasfGtxbp7yoe3m0tt9Rf0bDidvDnncvNGWndbErcBQEgdD-rsxcP9g__&Key-Pair-Id=KK4HN3OO4AT5R', 'Apple TV', 'https://media.movieofthenight.com/services/apple/logo-light-theme.svg', 'buy', 'https://tv.apple.com/ie/movie/anne-frank-parallel-stories/umc.cmc.75uleemiz5s8bx6ly9xtrxqqj?playableId=tvs.sbd.9001%3A1499887616', 'hd', '7.99 EUR'),
(3, '', 0, '', '#Captured', '', '', 'Horror', '', '', '', 'https://www.movieofthenight.com/media/image.svg?title=%23Captured&width=480&direction=horizontal', 'Apple TV', 'https://media.movieofthenight.com/services/apple/logo-light-theme.svg', 'buy', 'https://tv.apple.com/ie/movie/captured/umc.cmc.5hgzzvqd4k2vtip4gern4u1cb', 'hd', '2.49 EUR'),
(4, '', 0, '', '#FollowMe', 'A YouTuber and her two friends go missing from a motel in California while traveling from Los Angeles to San Francisco. A series of videos document their tragic fate after a post on social media containing #FollowMe.', '', 'Horror', '', '', '', 'https://cdn.movieofthenight.com/show/109246/poster/horizontal/en/480.jpg?Expires=1742318256&Signature=HfU02FcXsZp839MGnpNZGfpqJiTPymWvWyxYZCjEqVcMkt9kONYDUtfgUklQdQ43r3E6Elbpf23kb0isG8JH5sl4s21j-MZYYzShyH5DBmbXeOXmw7G1rIF6WhkRF86ekSQYKCS1Pz6zaFxgUNSasgrAG663WjgpPDhhsYIOOPk4d7AJvB6JFxkVk6JTjOC4DnIlSTw2cWgQx~QOpkutRiktMq~9tEKbHSRmIDp9Yodf5FsfckRYY0SJ1XBhSAN9eY5HDyWjSE8XOCJ6ZAzu96OThbJwPHaKh0wZKSg0b2DBtoQk05jnDudTSjtWrCON3v~TDtmIhm1yt4TpiGKVRg__&Key-Pair-Id=KK4HN3OO4AT5R', 'Apple TV', 'https://media.movieofthenight.com/services/apple/logo-light-theme.svg', 'buy', 'https://tv.apple.com/ie/movie/followme/umc.cmc.5oeet0dxkdwina5mv6hs0nzc5?playableId=tvs.sbd.9001%3A1465196383', 'hd', '8.99 EUR'),
(5, '', 0, '', '#GeorgeWashington', 'Meet the Father of Our Country in a whole new way as historians analyze George Washington\'s voluminous correspondence. Setting out his contacts and letters in the modern framework of a Facebook profile gives Washington\'s busy and productive career a new transparency.', '', 'Documentary', '', '', '', 'https://cdn.movieofthenight.com/show/335969/poster/horizontal/en/480.jpg?Expires=1742493901&Signature=XE0BjOr5xKsPeBAS7lVvR8dHxRhQw2YmQZjG0zLImPsGTCgQgydb~dd~c56bcq7akNhtIj1PQTvEFBViDYG0mSqpCY7HrvRAWmh8nA~W2NVvX25ikcMdfzD5kevIYR6OLWfj6augk9WxrkJMzFn~XM~2TnllX6J5dnoD0LFHxZThzrn3WDBad4T~EecXNYEiD23fQYZ4h9qJlPue-CtI-b8-NeJ67PClbVjKvo6UBwcsYB4LkD0Bqj9rdQGG1ggEJUqy1w-JJIHOIWszvlE7iHtZax4jkiDIe2tT~wqPAlCZHaZYvf61d45HJOkDjrbVnhzQmtuHfZrmDi01LVyUFQ__&Key-Pair-Id=KK4HN3OO4AT5R', 'Curiosity Stream', 'https://media.movieofthenight.com/services/curiosity/logo-light-theme.svg', 'subscription', 'https://curiositystream.com/video/1787', 'hd', ''),
(6, '', 0, '', '#Horror', 'Based on a horrifying true story, a group of prep-school girls experience a deadly night of terror when a vicious online game turns bloody. Chloë Sevigny & Timothy Hutton star.', '', 'Crime', '', '', '', 'https://cdn.movieofthenight.com/show/40188/poster/horizontal/en/480.jpg?Expires=1742210055&Signature=IAj6qwgPm~jyLLSz8pDlAylayicWTtzajr6MeLpmBQWo1MzEDUaZp4-OYRwiZE7ZIW2gelfHxogg49iUkn5wy-4VcynH7HDui46ePYcP1X1Uv5P4dV~QdHPENC6nHnJHZ4vQeqxr6Qaymtc4gzlz9boHsM9yMItsn9KaMATN34dPoRDFRAIQfbdNg8KX4YZolJLo4DE1LyDCS6Z9gO5DA-9kb7nFF1oo9ej5Lb3cx8bTPctCnNrHEEJX6aD1suqQMS32d3BHknz4MAjcuBFA51x2QPHISF5mdnnmQBt~iuBrtWXBkgIg30XGz5fcb2CVB40ao0q0i2YpNiF5YSHLkw__&Key-Pair-Id=KK4HN3OO4AT5R', 'Apple TV', 'https://media.movieofthenight.com/services/apple/logo-light-theme.svg', 'buy', 'https://tv.apple.com/ie/movie/horror/umc.cmc.2nf0pxxzu8z4moci2ynywis3c?playableId=tvs.sbd.9001%3A1100850948', 'sd', '7.99 EUR'),
(7, '', 0, '', '#IMomSoHard Live', 'Comedians Kristin Hensley and Jen Smedley of the viral webseries #IMOMSOHARD bring you their 2-person stand-up show! Combining stand-up & improvisation, the two share their honest and self-effacing humor on topics ranging from friendship, periods, sex after marriage, body image, and parenting failures. Because, hey: You’re not in this alone, ladies.', '', 'Comedy', '', '', '', 'https://cdn.movieofthenight.com/show/224511/poster/horizontal/en/480.jpg?Expires=1742259531&Signature=f~U08iWo-bnvHzgSk74L8palXpxJ3LmN6sFpcxW-AocpjwdHmQMXOTpCpf538YvMy-q1U~w6~R2VYNsIOyeRC3f9WOXhsjd9rrRM7E9fbi5gUPDs2uaTXHFgzqi4cQkV7XD36DIccAO0lPYmJrYhMJ5k-Iz7bOqDrbqqtfchfEytN7UgSBmeQRgPRqm7XJXo4LrFgwAL1f2-5WYtNE0P7Llg3IcSJYCeeUWmUosHBd3jzE9K8lkGQnaqLZR9P8n-gaajSX3Ny4AL880NcS7x2gTJMw-hNZUb~YX7TWb7-ELowZRw3AODIfk5IYkVVVUhk6MsklN6nnmeUYOyUACGcQ__&Key-Pair-Id=KK4HN3OO4AT5R', 'Prime Video', 'https://media.movieofthenight.com/services/prime/logo-light-theme.svg', 'subscription', 'https://www.primevideo.com/detail/0R9WOJ886VSXP8XR9LUVKBIV7J/ref=atv_dp', 'uhd', ''),
(8, '', 0, '', '#Like', 'Rosie takes justice into her own hands when she discovers her late sister’s mysterious bully is back online, trolling for new victims.', '', 'Thriller', '', '', '', 'https://cdn.movieofthenight.com/show/122751/poster/horizontal/en/480.jpg?Expires=1742358149&Signature=GYalyspqAk~QvXOd~dHbcJZRIq0ZdI81cMdrAirLd~OFzr4aq89Ywe17FSIDTFSdGKlchekgL8npx7IP9Abdmq75L8bJ3J6tzagGJbVCeP4ZDsGksI4hS-tjc61E5Nwv5pA-7Cz8H~~I407aXlJjBAwJA-jbRgT6YdJ7JM10N46Cp06756iaKun0-hXv2Bs1TAZRrh4AJug9sHk7or2v92-UQGOMUK5P99xApGt45wdYo6i0FgOfauhZpEgtn3ttxrHh21HZUaFKRoV~ckNOutAbqo24jKRdz9FRb03E953prwj3W07EEn4zaT7nF0DIMSZl7uYIlqUtU6WKWWDFqg__&Key-Pair-Id=KK4HN3OO4AT5R', 'Apple TV', 'https://media.movieofthenight.com/services/apple/logo-light-theme.svg', 'buy', 'https://tv.apple.com/ie/movie/like/umc.cmc.69f2xc86h8u45vac8mlshys2t?playableId=tvs.sbd.9001%3A1586352740', 'hd', '11.99 EUR'),
(9, '', 0, '', '#MayaLo', '#Mayalo is a road trip rom com which unravels conflicts, connections, and realizations of how Krish and Sindhu\'s lives were largely influenced by an overpowering and charming Maya.', '', 'Comedy', '', '', '', 'https://cdn.movieofthenight.com/show/5460937/poster/horizontal/en/480.jpg?Expires=1745334309&Signature=XfcIq0wuCmdOiF-XJzQo-1590trAA0BVAPE9p1h2r1H9UeFp3U6ipJLoxLibpl~RIKNasnE2w0suCTbE0ihBV8V46hMK2jxJ9iARg236fPNk3~TwFE5N~XLKsL2yg7U4G-484Od61sA1NgtzGFzpM45QYw31VOtrZATrWs8UQ751xNG8oDrZ28vaea3-6h9OKUbWsT4fl9kIE6Ny7xOWMTFIXNYj5keC3hswbfx2J-XghmGoxYjaTscbqe6~QTzFZ--QPaGmZKVWh8ODjRt~jwLvJ0Y18tlGT5WwyM7rlZPmApgMh7wVgpqkEvWJsUJl-4cagqBTKQ0esmMBrN5row__&Key-Pair-Id=KK4HN3OO4AT5R', 'Prime Video', 'https://media.movieofthenight.com/services/prime/logo-light-theme.svg', 'subscription', 'https://www.primevideo.com/detail/0GXAVD0766U4VX8LK9ALPGZEU5/ref=atv_dp', 'sd', ''),
(10, '', 0, '', '#O2LForever', 'Join Connor Franta, Jc Caylen, Kian Lawley, Ricky Dillon, Sam Pottorff and Trevor Moran as the YouTube supergroup Our 2nd Life (O2L) embarks upon their 2014 North American tour. Step inside their journey, from blogging in their bedrooms to performing in front of screaming fans across the country. This 95-minute adventure captures their launch into the next level of stardom while they try to stay grounded and maintain authentic connections with the communities that started it all.', '', 'Documentary', '', '', '', 'https://www.movieofthenight.com/media/image.svg?title=%23O2LForever&width=480&direction=horizontal', 'Apple TV', 'https://media.movieofthenight.com/services/apple/logo-light-theme.svg', 'buy', 'https://tv.apple.com/ie/movie/o2lforever/umc.cmc.34igbwiule0pob1dm6juuqz2n?playableId=tvs.sbd.9001%3A1028254540', 'sd', '8.99 EUR'),
(11, '', 0, '', '#SCREAMERS', 'Two internet gurus investigate the authenticity of a series of Screamers videos. As they unravel the source of the mysterious videos, they uncover something far more sinister and terrifying about the people behind them.', '', 'Horror', '', '', '', 'https://cdn.movieofthenight.com/show/83224/poster/horizontal/en/480.jpg?Expires=1742270338&Signature=HEMZwXZEqsxVdwvOum6kDAF3YeFzrllqRzGaaCiakJW9W7Gfs61PYNdBek5eGz3p4lgjeh2KQxONN8lLMXzXmn1yaug8NFjScZ5UVCEwkXO8Azav6d8vnVZjlWbUdV6Wswacu2mFokowYYlDZO4sfp-OrT7ZL65WWDd2wmucRfkN7MO5a0Cw5PK6WDWSm8JeG0PUnaqoXOgeqHDqDdDClmbslRXqS6lfF2mN1js3DxWfcvBmPItqqr25PFYa8CrNp8L0c~JCZCreuKlpFRYR04~fMvsApjoWMEkFuWbJAj4p15sjCrs8lyBV1pKwMHgxK6~IKD3Un-ILAC7pW9AtrA__&Key-Pair-Id=KK4HN3OO4AT5R', 'Prime Video', 'https://media.movieofthenight.com/services/prime/logo-light-theme.svg', 'subscription', 'https://www.primevideo.com/detail/0JCBSRPPN3Y6738S8KAWZ3JU3I/ref=atv_dp', 'sd', ''),
(12, '', 0, '', 'Selfie', 'Two days before their final exams, three teen girls make a seaside getaway to have the time of their lives.', '', 'Comedy', '', '', '', 'https://cdn.movieofthenight.com/show/64829/poster/horizontal/en/480.jpg?Expires=1742478666&Signature=bruR86m1V6dOFSfEzP7LAxPuT1FdfFTYxYTY3SL2k6n7NsB~67tgGQoRNgIpLdGhsyudCouzN0eJXVkzoRnTrreBVDzzV1esoYcPhwOfjvSkNKY7z3cNpTkcCEi9lP1Twvwbi5VAg~FUbDIi2aD7BxJCMxx0U00fZTvO5puCV6N~y1QtTK8IZnRYw~4SlUSrW3S6goyBFkhkU6B-9vm0ffSNeYLjk4hkQBs9pJMVytosprFLzZfFWE6okdDnmEQ3xd~pViJX5AZjT3t2VNE-Ow~81EUIA3Lbj~DVs~P1WBPhvrO-NIAp-kndaUQ-QnGUajy0ZD5yzS7M37B4lELdDA__&Key-Pair-Id=KK4HN3OO4AT5R', 'Netflix', 'https://media.movieofthenight.com/services/netflix/logo-light-theme.svg', 'subscription', 'https://www.netflix.com/title/81092768/', 'hd', ''),
(13, '', 0, '', '#Stuck', 'A hot one-night stand turns into an awkward morning after when GUY and HOLLY get STUCK in a dead-stopped traffic jam. As they begrudgingly get to know each other, we learn of their sexually raucous evening and then they\'re led to their surprising destiny.', '', 'Comedy', '', '', '', 'https://cdn.movieofthenight.com/show/81150/poster/horizontal/en/480.jpg?Expires=1742268799&Signature=Dwbx0sdKNPSMRuLXZK82bh77pK3L5WBZcOJW5ogtr4VoSZvxrfCNVU-VqYv4vQP4P5VzN8uqjs7hC3gOxwjT54X9j-qqhOfG6xGmzvsbKDSVDNZ-V4CoH0zRLT4EQjZak9DJagt3b8J80oMxRtFKSVlSN6A3MGVEw-degTysvYtl7rjiJnfWpslA2KVdKCjsNuWhvxdKZ767GHV97EdbLiG3Eo87Kwz0I6qT3U8qJp6UuaoO5FZ-eDWhYeyLNUxolJfEGlBRY0ARK6n2srxiZYc3c0ndottj7GNZ67Ai03rVeGKhDWCkSISYM~A4IPq6d4JXH0UV1ek0lSTpq8Y8VQ__&Key-Pair-Id=KK4HN3OO4AT5R', 'Prime Video', 'https://media.movieofthenight.com/services/prime/logo-light-theme.svg', 'subscription', 'https://www.primevideo.com/detail/0MNO3GMXMV0KRZ78GFD1H5GZHV/ref=atv_dp', 'sd', ''),
(14, '', 0, '', '#FriendButMarried', 'Pining for his high school crush for years, a young man puts up his best efforts to move out of the friend zone until she reveals she\'s getting married.', '', 'Comedy', '', '', '', 'https://cdn.movieofthenight.com/show/100605/poster/horizontal/en/480.jpg?Expires=1742296643&Signature=IO9R1JCKQ6xBTlwrqUIhLxR7rKcL5HCCANfVG-pqfDL8zPw~TYywoy6AgLOwX3MZNIbLiBCkzspjYDjum-abs2gBvDBzfMXxJi2kumFfMscgzwMi0XHWCtaJT0dP5SQ2hAeIqpCi4C5O2-FplFWQsSxqjE33hdFg6R8tlbQaggyg0TBz64QQZG2wCkMAgx-8gNT2vA2fgyB-IRZMJpmZcrYDDxoJxZJRbN4aUhdEdaGxmewXgqeHu7yI0dyCs7TDJ8XL-iWzhVl4n5eVre~3m5sY6EnTE0-069pywYJC3IuNNrsR~CRbpz~nuOczRAGEwqjd6NEUQTigrAu27ZIicQ__&Key-Pair-Id=KK4HN3OO4AT5R', 'Netflix', 'https://media.movieofthenight.com/services/netflix/logo-light-theme.svg', 'subscription', 'https://www.netflix.com/title/81260630/', 'hd', ''),
(15, '', 0, '', '#FriendButMarried 2', 'As Ayu and Ditto finally transition from best friends to newlyweds, a quick pregnancy creates uncertainty for the future of their young marriage.', '', 'Comedy', '', '', '', 'https://cdn.movieofthenight.com/show/131838/poster/horizontal/en/480.jpg?Expires=1742377883&Signature=b13-S9v5ql-EsY~piTQE9oHw6EeESXj5MJnaFOQbug7ABRtJmdLjjDZ-hL6XIUah9VtZdXkB2cPK-OwbgrAf~O38YwU2Gb2LsjaDh7TPLpbzI4VzLFU5dBqRqwxviLwOZdIDwNRJKyUvDtF6EU73BOnsHlDtk57fQ0QDQb4ZyJ1jnR5c5HE6~ckkI~W-NzKAm-1SnHH6pddO3CyY6UI6yk9RONFY-MoInrvh~VJVUFxHBc8DqPFWI96N5BV6JJ0FAR4McW3A5Ev4evB736xLoAc6EN42-tlu304jVK7hv~greZBWfjVvmD5Dcg0kaMyoSTebfia5lrjR9YhqYTXCDw__&Key-Pair-Id=KK4HN3OO4AT5R', 'Netflix', 'https://media.movieofthenight.com/services/netflix/logo-light-theme.svg', 'subscription', 'https://www.netflix.com/title/81260637/', 'hd', ''),
(16, '', 0, '', '#UNFIT: The Psychology of Donald Trump', 'Medical doctors and mental health professionals go on camera, on the record, for a discussion and science-based examination of the behaviour, psyche, condition, and stability of former President Donald Trump.', '', 'Documentary', '', '', '', 'https://cdn.movieofthenight.com/show/48570/poster/horizontal/en/480.jpg?Expires=1742355675&Signature=fWialUWGoqBiE-bzyNi54iqA3gpXIsMTxRr-JAWyUfZV7x0AJbIwBQiHGYiTu8etDOUw6bkx4kETdRA~OEQInVHY83tpOZV9yTAoxwP~amRsruoHJHmNpIK6OYBm49CqIDsmHugx4qfGRtWo0BvVGXPaqtTcY4XRJIC5U7z1Z61JRpaJiGvbgw-yDxCDAS57PclWidCQLtWmzYTpwOQ4CPgbxoAOKNZ7upSg9MaKcevHpUstM9UI-YMmilJZRNAzThdxQXsh-XFK5VYV4qQcu7n3YhpjowHj3Y3~Zlt2LIeNFqYxPa8xM1KBmTf-bUXkQQTwPBX9rTPcJSwTmytGRQ__&Key-Pair-Id=KK4HN3OO4AT5R', 'Prime Video', 'https://media.movieofthenight.com/services/prime/logo-light-theme.svg', 'subscription', 'https://www.primevideo.com/detail/0R9XXK0SVM26JTOXTLC3ZHTKLR/ref=atv_dp', 'sd', ''),
(17, '', 0, '', '#Victoria', 'Victoria moves from out of town into the poor inner city of New York with her father, the neighborhood drug dealer. She goes on a journey, seeking answers, justice, and revenge after her after was murdered by local competition. In the process of her revenge she finds herself lost of her own identity due to the opportunities placed in front of her. As the story progresses Victoria realizes that she doesn\'t want to live the lifestyle that she is living before it becomes to late.', '', 'Action', '', '', '', 'https://www.movieofthenight.com/media/image.svg?title=%23Victoria&width=480&direction=horizontal', 'Apple TV', 'https://media.movieofthenight.com/services/apple/logo-light-theme.svg', 'rent', 'https://tv.apple.com/ie/movie/victoria/umc.cmc.2h888xn3hbf6dnh513yli7mrz?playableId=tvs.sbd.9001%3A1328835352', 'hd', '4.99 EUR'),
(18, '', 0, '', '#Alive', 'As a grisly virus rampages a city, a lone man stays locked inside his apartment, digitally cut off from seeking help and desperate to find a way out.', '', 'Action', '', '', '', 'https://cdn.movieofthenight.com/show/9096/poster/horizontal/en/480.jpg?Expires=1741797227&Signature=L0-j9yTRd5vXspK18TzwkM0AMLYza8apozHeJCvoCprLaXmUXwijvkaQEZUlLJp-O8YDZM3jDR4G28zDQPVcRI7igLWudhylvsSvbwt3QPGDolPQs8c2mQGUefRqBhBwrx7eRYLgD3O779GNMPlS0WXBoJOxHl09cdU1Utozj~CPBMfn7B2~L5VYzg5uNF6BBbxktcNK6z9eWO198e16hghCFSloK8BPGZeIqTlYBzC3EvW9rIWSbNqcwkHc7P-EOl32CqX~LdpvanDLe0LV-XMU0xUzYfZ-FWZ4YxSnfr~fGaIvec5xqymMKjBiIVU4zLCxphq5shBvCwpbghf4iw__&Key-Pair-Id=KK4HN3OO4AT5R', 'Netflix', 'https://media.movieofthenight.com/services/netflix/logo-light-theme.svg', 'subscription', 'https://www.netflix.com/title/81240831/', 'hd', ''),
(19, '', 0, '', '$uperthief: Inside America\'s Biggest Bank Score', 'Superthief is a captivating firsthand look at the life of Phil Christopher, a career criminal, Mafia associate, and one of the most successful bank robbers in United States history. Through raw and candid interviews, the film delves into Christopher\'s brutal street and prison life, offering a behind-the-scenes look into the world professional crime. Superthief features interviews with Christopher, as well as former FBI agents, police officers, family members and old friends of Christopher.', '', 'Documentary', '', '', '', 'https://www.movieofthenight.com/media/image.svg?title=%24uperthief%3A+Inside+America%27s+Biggest+Bank+Score&width=480&direction=horizontal', 'Apple TV', 'https://media.movieofthenight.com/services/apple/logo-light-theme.svg', 'buy', 'https://tv.apple.com/ie/movie/superthief/umc.cmc.59xdbb35kgza8uk4cguqh4p5n?playableId=tvs.sbd.9001%3A741518645', 'hd', '11.99 EUR'),
(20, '', 0, '', '\'71', 'A young British soldier is accidentally abandoned by his unit following a riot on the streets of Belfast in 1971. Unable to tell friend from foe, and increasingly wary of his own comrades, the raw recruit must survive the night alone and find his way to safety through a disorientating, alien and deadly landscape.', '', 'Action', '', '', '', 'https://cdn.movieofthenight.com/show/7228/poster/horizontal/en/480.jpg?Expires=1741813811&Signature=IphDGlobQ9GgS6dViC1v8nI0HggxLfmG-DheMbUpSl46VC7nkbWWY7ySZpOYLYhjkuiK9Bj9psLj0zZsILYfGh2bH2jmDvP2vBEw2IbrNwDjt3ffEkg021Lf4c1zyPB~SOYpGxhW3IW9Zg-gdQ5j4HiF2VJVgxBaoHgShQWMLuE2jXGzYeZlo7wTLCZVjytnAbJYpJVc1NzTWyt1qX~JG3Ouq5e--zXsT1NP5pjeS8xfhOemT~-bnSzn1KR0pI3DE-Y7pwZ50L~E1-RKBrJvE9WTjSZuNWTquQmfLLxChDTHG5Rxv7OZZzvQIVLIwxyexMfstqkngnGpG53iuzFkrA__&Key-Pair-Id=KK4HN3OO4AT5R', 'Apple TV', 'https://media.movieofthenight.com/services/apple/logo-light-theme.svg', 'buy', 'https://tv.apple.com/ie/movie/71/umc.cmc.3dny8cyix1oyx7tl7p2r2l6hw?playableId=tvs.sbd.9001%3A926585730', 'sd', '4.99 EUR');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
